### ISSUE TITLE
Can you use fings on unmatched samples?

### ISSUE THREAD

**Issue by njbernstein** [cpwardell/FiNGS#2]

**Comment by cpwardell** [comment]
It would certainly run, but you would have to be careful with the results, you wouldn't want to filter anything because of a poor-quality unmatched normal sample.  I guess it might help clean up regions of poor quality alignment/sequencing.  I should really finish adding the tumor-only mode I've been intending to implement.  

If you've got a specific use-case or project in mind, feel free to email me and we can discuss it further.
